# Generated by Django 6.0.1 on 2026-01-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('litros', models.DecimalField(decimal_places=1, max_digits=5)),
                ('es_recarga', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='alimento',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
